# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui',
# licensing of 'form.ui' applies.
#
# Created: Tue Jan 22 18:39:54 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 463)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 5))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listViewFiles = QtWidgets.QListView(self.tab)
        self.listViewFiles.setObjectName("listViewFiles")
        self.horizontalLayout_3.addWidget(self.listViewFiles)
        self.listViewFormat = QtWidgets.QListView(self.tab)
        self.listViewFormat.setObjectName("listViewFormat")
        self.horizontalLayout_3.addWidget(self.listViewFormat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progbarTotal = QtWidgets.QProgressBar(self.tab)
        self.progbarTotal.setProperty("value", 24)
        self.progbarTotal.setObjectName("progbarTotal")
        self.verticalLayout.addWidget(self.progbarTotal)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.labelFileName = QtWidgets.QLabel(self.tab)
        self.labelFileName.setText("")
        self.labelFileName.setObjectName("labelFileName")
        self.horizontalLayout_4.addWidget(self.labelFileName)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.progbarCurrent = QtWidgets.QProgressBar(self.tab)
        self.progbarCurrent.setProperty("value", 24)
        self.progbarCurrent.setObjectName("progbarCurrent")
        self.verticalLayout.addWidget(self.progbarCurrent)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpen = QtWidgets.QPushButton(self.tab)
        self.btnOpen.setText("")
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnStart = QtWidgets.QPushButton(self.tab)
        self.btnStart.setText("")
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.tab)
        self.btnStop.setText("")
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.btnClearQueue = QtWidgets.QPushButton(self.tab)
        self.btnClearQueue.setObjectName("btnClearQueue")
        self.horizontalLayout.addWidget(self.btnClearQueue)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.crfSlider = QtWidgets.QSlider(self.widget)
        self.crfSlider.setOrientation(QtCore.Qt.Horizontal)
        self.crfSlider.setObjectName("crfSlider")
        self.gridLayout.addWidget(self.crfSlider, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.labelCRFVal = QtWidgets.QLabel(self.widget)
        self.labelCRFVal.setObjectName("labelCRFVal")
        self.gridLayout.addWidget(self.labelCRFVal, 3, 2, 1, 1)
        self.comboReso = QtWidgets.QComboBox(self.widget)
        self.comboReso.setObjectName("comboReso")
        self.gridLayout.addWidget(self.comboReso, 7, 2, 1, 1)
        self.textFrameRate = QtWidgets.QTextEdit(self.widget)
        self.textFrameRate.setObjectName("textFrameRate")
        self.gridLayout.addWidget(self.textFrameRate, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboPreset = QtWidgets.QComboBox(self.widget)
        self.comboPreset.setObjectName("comboPreset")
        self.gridLayout.addWidget(self.comboPreset, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.textDest = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.textDest.sizePolicy().hasHeightForWidth())
        self.textDest.setSizePolicy(sizePolicy)
        self.textDest.setObjectName("textDest")
        self.horizontalLayout_5.addWidget(self.textDest)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.widget, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Total:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Current:", None, -1))
        self.btnClearQueue.setText(QtWidgets.QApplication.translate("Form", "Clear Queue", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Form", "Main", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Resolution:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Preset:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Frame Rate:", None, -1))
        self.labelCRFVal.setText(QtWidgets.QApplication.translate("Form", "00", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "CRF:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Destination:", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QtWidgets.QApplication.translate("Form", "Video", None, -1))

